# Generated by Django 5.1.4 on 2025-01-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approuvé',
            field=models.BooleanField(default=True),
        ),
    ]
